import type { CheoneumCard } from "./cheoneum.types";

export const CHEONEUM_SINPAE_CARDS: CheoneumCard[] = [
  { id: "sinpae-01-cheongeuk", arcana: "sinpae", number: 1, name: "천극", hanja: "天極", image: "cheoneum-sinpae-01-cheongeuk.png", keywords: [] },
  { id: "sinpae-02-yeompa", arcana: "sinpae", number: 2, name: "염파", hanja: "炎波", image: "cheoneum-sinpae-02-yeompa.png", keywords: [] },
  { id: "sinpae-03-myeongjeon", arcana: "sinpae", number: 3, name: "명전", hanja: "明典", image: "cheoneum-sinpae-03-myeongjeon.png", keywords: [] },
  { id: "sinpae-04-taehwa", arcana: "sinpae", number: 4, name: "태화", hanja: "太和", image: "cheoneum-sinpae-04-taehwa.png", keywords: [] },
  { id: "sinpae-05-jieom", arcana: "sinpae", number: 5, name: "지엄", hanja: "地嚴", image: "cheoneum-sinpae-05-jieom.png", keywords: [] },
  { id: "sinpae-06-bowon", arcana: "sinpae", number: 6, name: "보원", hanja: "寶源", image: "cheoneum-sinpae-06-bowon.png", keywords: [] },
  { id: "sinpae-07-jaeun", arcana: "sinpae", number: 7, name: "자은", hanja: "慈恩", image: "cheoneum-sinpae-07-jaeun.png", keywords: [] },
  { id: "sinpae-08-wolyeong", arcana: "sinpae", number: 8, name: "월영", hanja: "月影", image: "cheoneum-sinpae-08-wolyeong.png", keywords: [] },
  { id: "sinpae-09-amnyu", arcana: "sinpae", number: 9, name: "암류", hanja: "暗流", image: "cheoneum-sinpae-09-amnyu.png", keywords: [] },
  { id: "sinpae-10-gyeongyeon", arcana: "sinpae", number: 10, name: "경연", hanja: "慶宴", image: "cheoneum-sinpae-10-gyeongyeon.png", keywords: [] },
  { id: "sinpae-11-hwaldo", arcana: "sinpae", number: 11, name: "활도", hanja: "活刀", image: "cheoneum-sinpae-11-hwaldo.png", keywords: [] },
  { id: "sinpae-12-taeheo", arcana: "sinpae", number: 12, name: "태허", hanja: "太虛", image: "cheoneum-sinpae-12-taeheo.png", keywords: [] },
];

export const CHEONEUM_JINPAE_CARDS: CheoneumCard[] = [
  { id: "jinpae-01-gapja-gimbyeon", arcana: "jinpae", number: 1, ganji: "갑자", name: "김변장군", image: "cheoneum-jinpae-01-gapja-gimbyeon.png", keywords: [] },
  { id: "jinpae-02-byeongja-gwakga", arcana: "jinpae", number: 2, ganji: "병자", name: "곽가장군", image: "cheoneum-jinpae-02-byeongja-gwakga.png", keywords: [] },
  { id: "jinpae-03-muja-chudang", arcana: "jinpae", number: 3, ganji: "무자", name: "추당장군", image: "cheoneum-jinpae-03-muja-chudang.png", keywords: [] },
  { id: "jinpae-04-gyeongja-nobi", arcana: "jinpae", number: 4, ganji: "경자", name: "노비장군", image: "cheoneum-jinpae-04-gyeongja-nobi.png", keywords: [] },
  { id: "jinpae-05-imja-gudeok", arcana: "jinpae", number: 5, ganji: "임자", name: "구덕장군", image: "cheoneum-jinpae-05-imja-gudeok.png", keywords: [] },
  { id: "jinpae-06-eulchuk-jinjae", arcana: "jinpae", number: 6, ganji: "을축", name: "진재장군", image: "cheoneum-jinpae-06-eulchuk-jinjae.png", keywords: [] },
  { id: "jinpae-07-jeongchuk-tanggeum", arcana: "jinpae", number: 7, ganji: "정축", name: "탕금장군", image: "cheoneum-jinpae-07-jeongchuk-tanggeum.png", keywords: [] },
  { id: "jinpae-08-gichuk-buu", arcana: "jinpae", number: 8, ganji: "기축", name: "부우장군", image: "cheoneum-jinpae-08-gichuk-buu.png", keywords: [] },
  { id: "jinpae-09-sinchuk-yangsin", arcana: "jinpae", number: 9, ganji: "신축", name: "양신장군", image: "cheoneum-jinpae-09-sinchuk-yangsin.png", keywords: [] },
  { id: "jinpae-10-gyechuk-judeuk", arcana: "jinpae", number: 10, ganji: "계축", name: "주득장군", image: "cheoneum-jinpae-10-gyechuk-judeuk.png", keywords: [] },
  { id: "jinpae-11-gabin-jangjo", arcana: "jinpae", number: 11, ganji: "갑인", name: "장조장군", image: "cheoneum-jinpae-11-gabin-jangjo.png", keywords: [] },
  { id: "jinpae-12-byeongin-hamjang", arcana: "jinpae", number: 12, ganji: "병인", name: "함장장군", image: "cheoneum-jinpae-12-byeongin-hamjang.png", keywords: [] },
  { id: "jinpae-13-muin-noseon", arcana: "jinpae", number: 13, ganji: "무인", name: "노선장군", image: "cheoneum-jinpae-13-muin-noseon.png", keywords: [] },
  { id: "jinpae-14-gyeongin-uhwan", arcana: "jinpae", number: 14, ganji: "경인", name: "우환장군", image: "cheoneum-jinpae-14-gyeongin-uhwan.png", keywords: [] },
  { id: "jinpae-15-imin-haak", arcana: "jinpae", number: 15, ganji: "임인", name: "하악장군", image: "cheoneum-jinpae-15-imin-haak.png", keywords: [] },
  { id: "jinpae-16-eulmyo-mancheong", arcana: "jinpae", number: 16, ganji: "을묘", name: "만청장군", image: "cheoneum-jinpae-16-eulmyo-mancheong.png", keywords: [] },
  { id: "jinpae-17-jeongmyo-simheung", arcana: "jinpae", number: 17, ganji: "정묘", name: "심흥장군", image: "cheoneum-jinpae-17-jeongmyo-simheung.png", keywords: [] },
  { id: "jinpae-18-gimyo-yongjung", arcana: "jinpae", number: 18, ganji: "기묘", name: "용중장군", image: "cheoneum-jinpae-18-gimyo-yongjung.png", keywords: [] },
  { id: "jinpae-19-sinmyo-peomsu", arcana: "jinpae", number: 19, ganji: "신묘", name: "펌수장군", image: "cheoneum-jinpae-19-sinmyo-peomsu.png", keywords: [] },
  { id: "jinpae-20-gyemyo-pisi", arcana: "jinpae", number: 20, ganji: "계묘", name: "피시장군", image: "cheoneum-jinpae-20-gyemyo-pisi.png", keywords: [] },
  { id: "jinpae-21-gapjin-iseong", arcana: "jinpae", number: 21, ganji: "갑진", name: "이성장군", image: "cheoneum-jinpae-21-gapjin-iseong.png", keywords: [] },
  { id: "jinpae-22-byeongjin-sina", arcana: "jinpae", number: 22, ganji: "병진", name: "신아장군", image: "cheoneum-jinpae-22-byeongjin-sina.png", keywords: [] },
  { id: "jinpae-23-mujin-jodal", arcana: "jinpae", number: 23, ganji: "무진", name: "조달장군", image: "cheoneum-jinpae-23-mujin-jodal.png", keywords: [] },
  { id: "jinpae-24-gyeongjin-dongdeok", arcana: "jinpae", number: 24, ganji: "경진", name: "동덕장군", image: "cheoneum-jinpae-24-gyeongjin-dongdeok.png", keywords: [] },
  { id: "jinpae-25-imjin-paengtae", arcana: "jinpae", number: 25, ganji: "임진", name: "팽태장군", image: "cheoneum-jinpae-25-imjin-paengtae.png", keywords: [] },
  { id: "jinpae-26-eulsa-osu", arcana: "jinpae", number: 26, ganji: "을사", name: "오수장군", image: "cheoneum-jinpae-26-eulsa-osu.png", keywords: [] },
  { id: "jinpae-27-jeongsa-yangeon", arcana: "jinpae", number: 27, ganji: "정사", name: "양언장군", image: "cheoneum-jinpae-27-jeongsa-yangeon.png", keywords: [] },
  { id: "jinpae-28-gisa-gwakchan", arcana: "jinpae", number: 28, ganji: "기사", name: "곽찬장군", image: "cheoneum-jinpae-28-gisa-gwakchan.png", keywords: [] },
  { id: "jinpae-29-sinsa-jeongdan", arcana: "jinpae", number: 29, ganji: "신사", name: "정단장군", image: "cheoneum-jinpae-29-sinsa-jeongdan.png", keywords: [] },
  { id: "jinpae-30-gyesa-seodan", arcana: "jinpae", number: 30, ganji: "계사", name: "서단장군", image: "cheoneum-jinpae-30-gyesa-seodan.png", keywords: [] },
  { id: "jinpae-31-gabo-jangsa", arcana: "jinpae", number: 31, ganji: "갑오", name: "장사장군", image: "cheoneum-jinpae-31-gabo-jangsa.png", keywords: [] },
  { id: "jinpae-32-byeongo-muncheol", arcana: "jinpae", number: 32, ganji: "병오", name: "문철장군", image: "cheoneum-jinpae-32-byeongo-muncheol.png", keywords: [] },
  { id: "jinpae-33-muo-igyeong", arcana: "jinpae", number: 33, ganji: "무오", name: "이경장군", image: "cheoneum-jinpae-33-muo-igyeong.png", keywords: [] },
  { id: "jinpae-34-gyeongo-wangje", arcana: "jinpae", number: 34, ganji: "경오", name: "왕제장군", image: "cheoneum-jinpae-34-gyeongo-wangje.png", keywords: [] },
  { id: "jinpae-35-imo-yukmyeong", arcana: "jinpae", number: 35, ganji: "임오", name: "육명장군", image: "cheoneum-jinpae-35-imo-yukmyeong.png", keywords: [] },
  { id: "jinpae-36-eulmi-busang", arcana: "jinpae", number: 36, ganji: "을미", name: "부상장군", image: "cheoneum-jinpae-36-eulmi-busang.png", keywords: [] },
  { id: "jinpae-37-jeongmi-mubyeong", arcana: "jinpae", number: 37, ganji: "정미", name: "무병장군", image: "cheoneum-jinpae-37-jeongmi-mubyeong.png", keywords: [] },
  { id: "jinpae-38-gimi-yangseon", arcana: "jinpae", number: 38, ganji: "기미", name: "양선장군", image: "cheoneum-jinpae-38-gimi-yangseon.png", keywords: [] },
  { id: "jinpae-39-sinmi-iso", arcana: "jinpae", number: 39, ganji: "신미", name: "이소장군", image: "cheoneum-jinpae-39-sinmi-iso.png", keywords: [] },
  { id: "jinpae-40-gyemi-wiin", arcana: "jinpae", number: 40, ganji: "계미", name: "위인장군", image: "cheoneum-jinpae-40-gyemi-wiin.png", keywords: [] },
  { id: "jinpae-41-gapsin-bangsa", arcana: "jinpae", number: 41, ganji: "갑신", name: "방사장군", image: "cheoneum-jinpae-41-gapsin-bangsa.png", keywords: [] },
  { id: "jinpae-42-byeongsin-gwanjung", arcana: "jinpae", number: 42, ganji: "병신", name: "관중장군", image: "cheoneum-jinpae-42-byeongsin-gwanjung.png", keywords: [] },
  { id: "jinpae-43-musin-seoho", arcana: "jinpae", number: 43, ganji: "무신", name: "서호장군", image: "cheoneum-jinpae-43-musin-seoho.png", keywords: [] },
  { id: "jinpae-44-gyeongsin-mojae", arcana: "jinpae", number: 44, ganji: "경신", name: "모재장군", image: "cheoneum-jinpae-44-gyeongsin-mojae.png", keywords: [] },
  { id: "jinpae-45-imsin-yuwang", arcana: "jinpae", number: 45, ganji: "임신", name: "유왕장군", image: "cheoneum-jinpae-45-imsin-yuwang.png", keywords: [] },
  { id: "jinpae-46-euryu-jangsung", arcana: "jinpae", number: 46, ganji: "을유", name: "장숭장군", image: "cheoneum-jinpae-46-euryu-jangsung.png", keywords: [] },
  { id: "jinpae-47-jeongyu-dangsa", arcana: "jinpae", number: 47, ganji: "정유", name: "당사장군", image: "cheoneum-jinpae-47-jeongyu-dangsa.png", keywords: [] },
  { id: "jinpae-48-giyu-jeongbo", arcana: "jinpae", number: 48, ganji: "기유", name: "정보장군", image: "cheoneum-jinpae-48-giyu-jeongbo.png", keywords: [] },
  { id: "jinpae-49-sinyu-seokjeong", arcana: "jinpae", number: 49, ganji: "신유", name: "석정장군", image: "cheoneum-jinpae-49-sinyu-seokjeong.png", keywords: [] },
  { id: "jinpae-50-gyeyu-gangji", arcana: "jinpae", number: 50, ganji: "계유", name: "강지장군", image: "cheoneum-jinpae-50-gyeyu-gangji.png", keywords: [] },
  { id: "jinpae-51-gapsul-sigwang", arcana: "jinpae", number: 51, ganji: "갑술", name: "시광장군", image: "cheoneum-jinpae-51-gapsul-sigwang.png", keywords: [] },
  { id: "jinpae-52-byeongsul-baekmin", arcana: "jinpae", number: 52, ganji: "병술", name: "백민장군", image: "cheoneum-jinpae-52-byeongsul-baekmin.png", keywords: [] },
  { id: "jinpae-53-musul-gangmu", arcana: "jinpae", number: 53, ganji: "무술", name: "강무장군", image: "cheoneum-jinpae-53-musul-gangmu.png", keywords: [] },
  { id: "jinpae-54-gyeongsul-yehwasim", arcana: "jinpae", number: 54, ganji: "경술", name: "예화심장군", image: "cheoneum-jinpae-54-gyeongsul-yehwasim.png", keywords: [] },
  { id: "jinpae-55-imsul-heungchung", arcana: "jinpae", number: 55, ganji: "임술", name: "흥충장군", image: "cheoneum-jinpae-55-imsul-heungchung.png", keywords: [] },
  { id: "jinpae-56-eulhae-imbo", arcana: "jinpae", number: 56, ganji: "을해", name: "임보장군", image: "cheoneum-jinpae-56-eulhae-imbo.png", keywords: [] },
  { id: "jinpae-57-jeonghae-bongje", arcana: "jinpae", number: 57, ganji: "정해", name: "봉제장군", image: "cheoneum-jinpae-57-jeonghae-bongje.png", keywords: [] },
  { id: "jinpae-58-gihae-satae", arcana: "jinpae", number: 58, ganji: "기해", name: "사태장군", image: "cheoneum-jinpae-58-gihae-satae.png", keywords: [] },
  { id: "jinpae-59-sinhae-yeopgyeon", arcana: "jinpae", number: 59, ganji: "신해", name: "엽견장군", image: "cheoneum-jinpae-59-sinhae-yeopgyeon.png", keywords: [] },
  { id: "jinpae-60-gyehae-ujeong", arcana: "jinpae", number: 60, ganji: "계해", name: "우정장군", image: "cheoneum-jinpae-60-gyehae-ujeong.png", keywords: [] },
];

export const CHEONEUM_CARDS: CheoneumCard[] = [
  ...CHEONEUM_SINPAE_CARDS,
  ...CHEONEUM_JINPAE_CARDS,
];

